name: Add comment
on: 
  issue_comment:
    types:
      - created

jobs:
  add-comment:
    if: github.event.issue.author_association == 'OWNER' && contains(github.event.comment.body, 'ping')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "Pong!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
